export default {
    img_user: '/images/img_user.png',
    ic_chevron_down: '/images/ic_chevron_down.png',
    img_main_backdrop: '/images/img_main_backdrop.png',
    img_cc: '/images/img_cc.png',
    img_chart: '/images/img_chart.png',
    img_percent: '/images/img_percent.png',
    img_cards: '/images/img_cards.png',
    img_shield: '/images/img_shield.png',
    img_pf_1: '/images/img_pf_1.png',
    img_pf_2: '/images/img_pf_2.png',
    img_pf_3: '/images/img_pf_3.png',
    img_pf_4: '/images/img_pf_4.png',
    img_cc_1: '/images/img_cc_1.png',
    img_cc_2: '/images/img_cc_2.png',
    img_cc_3: '/images/img_cc_3.png',
    ic_arrow: '/images/ic_arrow.png',
};
