export default {
    img_user: '/images/img_user.png',
    ic_chevron_down: '/images/ic_chevron_down.png',
    img_main_backdrop: '/images/img_main_backdrop.png',
    img_cc: '/images/img_cc.png',
    img_chart: '/images/img_chart.png',
    img_percent: '/images/img_percent.png',
    img_cards: '/images/img_cards.png',
    img_shield: '/images/img_shield.png',
    img_pf_1: '/images/img_pf_1.png',
    img_pf_2: '/images/img_pf_2.png',
    img_pf_3: '/images/img_pf_3.png',
    img_pf_4: '/images/img_pf_4.png',
    img_cc_1: '/images/img_cc_1.png',
    img_cc_2: '/images/img_cc_2.png',
    img_cc_3: '/images/img_cc_3.png',
    ic_arrow: '/images/ic_arrow.png',
    img_grid_left: '/images/img_grid_left.png',
    img_grid_right: '/images/img_grid_right.png',
    img_cc_backdrop:'/images/img_cc_backdrop.png',
    img_lounge_1: '/images/img_lounge_1.png',
    img_lounge_2: '/images/img_lounge_2.png',
    img_lounge_3: '/images/img_lounge_3.png',
    img_place_1: '/images/img_place_1.png',
    img_place_2: '/images/img_place_2.png',
    img_place_3: '/images/img_place_3.png',
    img_ratan_tata: '/images/img_ratan_tata.png',
    img_instagram: '/images/img_instagram.png',
    img_twitter: '/images/img_twitter.png',
    img_google_play: '/images/img_google_play.png',
    img_app_store: '/images/img_app_store.png',
    img_spotlight: '/images/img_spotlight.png',
};
